### ISSUE TITLE
Need another language

### ISSUE THREAD

**Issue by ApexAlen** [DmitriySalnikov/OBSNotifier#11]
### Feature description

Can you provide a prompt in Simplified Chinese? If possible, I would greatly appreciate it

### Implementation Ideas

You can also use machine translation, which will be very simple

**Comment by DmitriySalnikov** [comment]
It can be useful. But I would add a system for localization into many languages.
So now I'm thinking about integrating with Crowdin. Can you help with localization correction later?

But I'm not sure what difficulties I'll have to face, so I can't guarantee that the update will be released in a few days.

**Comment by ApexAlen** [comment]
I'm very sorry, I only saw the message now. I was previously trapped by something and I will use the link you provided to make corrections to the Simplified Chinese translation. Thank you.

**Comment by ApexAlen** [comment]
I have made additions and adjustments to Simplified Chinese

**Comment by DmitriySalnikov** [comment]
> I have made additions and adjustments to Simplified Chinese

After a quick look, I noticed an error here. Curly brackets or numbers have different codes.
![image](https://github.com/DmitriySalnikov/OBSNotifier/assets/7782218/6194754c-a2b4-4d47-8e31-52376d7a1ace)

![image](https://github.com/DmitriySalnikov/OBSNotifier/assets/7782218/97ea1cb8-6c06-42ca-9623-0df10dbd8255)

After these corrections, you can approve the translations
![image](https://github.com/DmitriySalnikov/OBSNotifier/assets/7782218/ba9ee7bd-8bab-4256-9538-942d6c9f52d6)

After some time I will release an update with this translation

**Comment by ApexAlen** [comment]
I have noticed these issues and have made modifications to them

**Comment by DmitriySalnikov** [comment]
Thanks.
Also, if you haven't noticed yet, I've added contextual images and labels for all the strings.

![image](https://github.com/DmitriySalnikov/OBSNotifier/assets/7782218/72a9ae3b-78ea-42ea-9e8b-dbe0f8862a6d)
(It was very boring and tedious 😫)

I hope this helps at least a little

**Comment by ApexAlen** [comment]
Thank you. They are very useful and can help me easily understand its purpose instead of opening the program

**Comment by ApexAlen** [comment]
![QQ图片20230904200710](https://github.com/DmitriySalnikov/OBSNotifier/assets/142656012/4086596a-94a3-4efd-8d08-cc4be3293c78)
Their functions are almost completely duplicated. If possible, please add a separate save setting information for Reset to current, and when you click Reset to current, it will be restored to the user-defined option instead of the default value

**Comment by DmitriySalnikov** [comment]
> Their functions are almost completely duplicated.

Not really. `Reset to current` resets to the current saved state.

https://github.com/DmitriySalnikov/OBSNotifier/assets/7782218/4204ae41-23fe-4610-b16a-7e8d9a646137

**Comment by ApexAlen** [comment]
Sorry, I overlooked some key points

**Comment by ApexAlen** [comment]
I have verified and approved all accurate translations in lang.xaml. Thank you for developing this program that solved my major problem

**Comment by DmitriySalnikov** [comment]
I will soon try to fix the localization update script and provide an updated version of the program for testing.

**Comment by DmitriySalnikov** [comment]
Here is an updated application https://github.com/DmitriySalnikov/OBSNotifier/actions/runs/6075937856

I also noticed this translation because of several mentions of the `.lua` file.
![image](https://github.com/DmitriySalnikov/OBSNotifier/assets/7782218/74c9cc78-7902-4fb7-8884-d373f1d1930a)

_I will note once again that I would not like to mention the specific names of files, folders and the name of this application, because they may change in the future. If I need to specify a name or path, I will add {_}._

If I understood correctly, then your translation says that first I need to remove the file name from the pasted path, and then select the file. But you can just paste the whole path as it is written in the instructions and click open.

https://github.com/DmitriySalnikov/OBSNotifier/assets/7782218/f8ee5f82-0635-4dea-a7aa-941a5e91f1a3

And this checkmark simply lowers the priority of the process (`Run with lower priority`)
![image](https://github.com/DmitriySalnikov/OBSNotifier/assets/7782218/fe6e0df2-c278-438c-b7d0-1288f66fb1de)

**Comment by ApexAlen** [comment]
Yes Sir I have refined and deleted the description of the path and file lua and replaced them with following the path copied to the clipboard

**Comment by DmitriySalnikov** [comment]
Update released, thanks!
https://github.com/DmitriySalnikov/OBSNotifier/releases/tag/1.3.1
